# Generated by Django 3.1 on 2020-08-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberactivityapp', '0002_auto_20200808_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.UUIDField(default='8AEC27', editable=False, primary_key=True, serialize=False),
        ),
    ]
