# Generated by Django 3.1 on 2020-08-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberactivityapp', '0004_auto_20200808_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.UUIDField(default='50F5F68EFC0048A1BD9F2C324C07449A', editable=False, primary_key=True, serialize=False),
        ),
    ]
