# Generated by Django 3.1 on 2020-08-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberactivityapp', '0005_auto_20200808_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.UUIDField(default='1C0881FE65DD4225BD48074F95464673', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
