# Generated by Django 3.1 on 2020-08-09 01:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('memberactivityapp', '0006_auto_20200809_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
